source 'https://rubygems.org'

# Declare your gem's dependencies in jobs.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

group :development, :test do
  gem 'rspec-rails', '~> 3.3.3'
  gem 'factory_girl_rails', '~> 4.4.1'
end

gem 'sidekiq'
# Whenever is a Ruby gem that provides a clear syntax for writing and deploying cron jobs
gem 'clockwork'

# gem 'daemons'

# gem 'clockworkd'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

