
ent_web:
  build: .

#  container_name: ent_web_dev

  # provide custom environment variables
  # env_file:
  #  - config/docker_dev.env

  # You can overwrite env variables here
  environment:
    - RAILS_ENV=production

  ports:
    - "32010:3000"
    - "80:80"

  links:
    - ent_data:ent_data
    - ent_postgres:ent_postgres
    - ent_solr:ent_solr
    - ent_redis:ent_redis
    - ent_mongodb:ent_mongodb

#    - ent_cms:ent_cms

ent_data:
  image: postgres:9.3.10
  container_name: ent_data
  volumes:
    - /var/lib/postgresql/data
  command: /bin/true

ent_postgres:
  image:  grahamgilbert/postgres:latest
  ports:
    - "5432:5432"
  volumes_from:
    - ent_data
  container_name: ent_postgres
  environment:
    DB_NAME:  enterprise_rails_development
    DB_USER:  postgres_rails
    DB_PASS:  postgres_rails

ent_solr:
  image: pataquets/solr
  ports:
    - "8983:8983"
  container_name: ent_solr
  volumes:
  # NOTE: for docker-machine the volumes are mapped from localhost->docker-machine->container. So we can expose the local solr configuration and data to container.
  # This is not at all obvious. In order for this to work with a remote docker host, the localhost and docker host directories needs to be synced up manually.
  # Also note that I had to use an older version (4.10) of solr image. The latest version is not compatible with what is used in the project (4.2).
  # Also note the location of solr configuration and data on image is different than standard solr configuration. 
    - /root/ent_rails/solr:/opt/solr/example/solr
ent_redis:
  image: redis:latest
  ports:
    - "6379:6379"
  container_name: ent_redis

ent_mongodata:
  image: tutum/mongodb
  volumes:
    - /data/db
  container_name: ent_mongodata
  command: /bin/sh

ent_mongodb:
  image: tutum/mongodb
  ports:
    - 27017:27017
  volumes_from:
    - ent_mongodata
  container_name: ent_mongodb
  environment:
    MONGODB_PASS: mongodb_rails

#ent_cms:
#  image: prakash0450/enterprise_cms:do_v1
#  ports:
#    - "32020:3009"
#  container_name: ent_cms
#  environment:
#    RAILS_ENV: production
#    # MONGODB_HOST: 192.168.0.20
#    MONGODB_HOST: 104.131.20.197
#    MONGODB_PORT: 27017
#    MONGODB_USER: admin
#    MONGODB_PASSWD: mongodb_rails


# command: --smallfiles --rest --auth

#  external_links:
#    - sad_wright:postgres
#    - ent_solr:solr



