FROM ruby:2.2
RUN apt-get update \
    && apt-get install -y build-essential nodejs npm nodejs-legacy postgresql-client emacs nginx
RUN npm install -g phantomjs
RUN mkdir /myapp
RUN mkdir /tmp/gems

# WORKDIR /tmp/gems
COPY Gemfile.app Gemfile.app
RUN bundle install --gemfile=Gemfile.app --development --test

ADD . /myapp

WORKDIR /myapp

# VOLUME .:/myapp

ENV RAILS_ENV=production
ENV RAILS_PORT=3000
ENV RAILS_HOME=/myapp
ENV SECRET_KEY_BASE=c733aabc894e4464031641d68f9c2066df51d177d793f462892b20ec8c50df7c06aa30fdd1153c19e6487684254fface62f09af847ad4cfb85c537d84e3e3a38


# bundle install needs to be after adding rails dir since Gemfile refers to engines in components dir of app.

# RUN bundle install

RUN bundle install --gemfile=Gemfile --development --test


EXPOSE 3000
#This env. variables will be used by database.yml to connect to postgresSQL
ENV DATABASE_HOST=<%= ENV['DATABASE_HOST'] %>
ENV DATABASE_PORT=<%= ENV['DATABASE_PORT'] %>
ENV DATABASE_USER=<%= ENV['DATABASE_USER'] %>
ENV DATABASE_PASSWD=<%= ENV['DATABASE_PASSWD'] %>

#This env. variables will be used by sunspot.yml to connect to Solr
ENV SOLR_HOST=<%= ENV['SOLR_HOST'] %>
ENV SOLR_PORT=<%= ENV['SOLR_PORT'] %>

#This env. variables will be used by sunspot.yml to connect to Solr
ENV REDIS_HOST=<%= ENV['REDIS_HOST'] %>
ENV REDIS_PORT=<%= ENV['REDIS_PORT'] %>
ENV REDIS_URL=redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>

# process env. variables on redis.conf file. Redis does not support env variables in its configuration file.
RUN erb ./config/redis.conf.erb > ./config/redis.conf

# You have to run this CMD with 0.0.0.0 IP address for port mapping to work in Docker container. Very strange.
# NOTE: the rake commands are being run here before starting rails to setup database. There has to be a better way. Need to investigate.
CMD rake db:drop \
    && rake db:create \
    && rake db:migrate \
    && rake sample_data:load \
    && rake authorization:seed \
    && rake assets:precompile \
    && ./scripts/start_sidekiq.sh \
    && ./scripts/start_clockwork.sh \
    && rails server -e production -b 0.0.0.0











