source 'https://rubygems.org'

# Declare your gem's dependencies in authorization.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

path '../' do
  gem 'persistence', '0.0.1'
  gem 'web_style'
end

# NOTE: Needed to make a minor change to gretel to work with Rails 4.2. see https://github.com/prakash-alpine/gretel
gem 'gretel', :github => 'prakash-alpine/gretel'
# gem 'gretel', '3.0.8'
gem 'active_model_serializers'
gem 'responders', '~> 2.0'

# gem 'jbuilder'

#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
