source 'https://rubygems.org'

# Declare your gem's dependencies in search.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'rspec-rails', '~> 3.3.3'
gem 'factory_girl_rails', '~> 4.4.1'
gem 'sunspot_rails', '2.2.0'
gem 'sunspot_solr', '2.2.0', :group => :development

# gem 'responders', '~> 2.0'

gem 'activerecord-postgresql-adapter'
#gem 'sqlite3'

path '../' do
  gem 'persistence', '0.0.1'
end


# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

